application:
  port: 5000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
